// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfV2TO-U4_9KJcKnaOSUDjPZPpJWwRekg',
    appId: '1:324741421194:web:df1dbdd9541d368d1c3573',
    messagingSenderId: '324741421194',
    projectId: 'subpulse-d358b',
    authDomain: 'subpulse-d358b.firebaseapp.com',
    storageBucket: 'subpulse-d358b.firebasestorage.app',
    measurementId: 'G-HCXN5XPBSG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASz_o7GmXg6VnWx8RNvy9gVvoz-OBMkwc',
    appId: '1:324741421194:android:256c47c8e1d985b01c3573',
    messagingSenderId: '324741421194',
    projectId: 'subpulse-d358b',
    storageBucket: 'subpulse-d358b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqfX6yyDGWa9cI7J_6v-7ZVZfnsd5MLFc',
    appId: '1:324741421194:ios:05ea30dcb47a2f901c3573',
    messagingSenderId: '324741421194',
    projectId: 'subpulse-d358b',
    storageBucket: 'subpulse-d358b.firebasestorage.app',
    iosBundleId: 'com.example.mobilproje',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqfX6yyDGWa9cI7J_6v-7ZVZfnsd5MLFc',
    appId: '1:324741421194:ios:05ea30dcb47a2f901c3573',
    messagingSenderId: '324741421194',
    projectId: 'subpulse-d358b',
    storageBucket: 'subpulse-d358b.firebasestorage.app',
    iosBundleId: 'com.example.mobilproje',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfV2TO-U4_9KJcKnaOSUDjPZPpJWwRekg',
    appId: '1:324741421194:web:8de6d64c39c652241c3573',
    messagingSenderId: '324741421194',
    projectId: 'subpulse-d358b',
    authDomain: 'subpulse-d358b.firebaseapp.com',
    storageBucket: 'subpulse-d358b.firebasestorage.app',
    measurementId: 'G-H73MZQ1W8N',
  );
}
